### PR TITLE
Quick fix for issue #58

### PR DESCRIPTION
**Pull request by kmcarter**
Though it should probably be using the queue worker to handle download tasks.

### CODE REVIEW

**Comment by wilr** [comment]
Thanks for the patch. Agree a queue worker would be the best way to approach it. Any suggestions for existing node package to provide simple queuing?

**Comment by kmcarter** [comment]
I am not familiar with the Node ecosystem (though that is on my very long to-learn list), so unfortunately no. :(

**Comment by wilr** [comment]
Ha me neither to some degree! Wish I did more. I'll take a look and see what we could build on.

Thanks again.

**Comment by kmcarter** [comment]
My pleasure! This package has saved me a lot of time and annoyance, so thank YOU.

**Pull request merged**
